# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r:
  - release
  - devel
os:
  - linux
  - osx
sudo: false

matrix:
  exclude:
    - r: devel
      os: osx

# env:
#   matrix:
#     - SYMENGINE_COMMIT=master
#     - SYMENGINE_COMMIT=535ff3c7716c8a3ca4254e51b1b9cd5baf5d8b19

apt_packages:
  - cmake
  - libgmp-dev
  - libmpfr-dev
  - libmpc-dev
  - devscripts

#brew_packages:
#  - cmake
#  - gmp
#  - mpfr
#  - libmpc

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install cmake gmp mpfr libmpc checkbashisms || true; fi
  
warnings_are_errors: true

notifications:
  email: false
