# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
before_install:
  - sudo add-apt-repository ppa:symengine/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libsymengine-dev -y
