# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r:
  - release
os:
  - linux
  - osx
sudo: false

## FIXME: warnings should be errors when the package is stable
warnings_are_errors: false

notifications:
  email: false

## Use bin/install_travis.sh to install symengine C++ library
before_install:
- bash tools/setup_travis.sh
- export PATH="$HOME/conda_root/bin:$PATH"
- source activate $HOME/our_usr

