# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

apt_packages:
  - libmpc-dev
  - libmpfr-dev

before_script:
  - cd /tmp
  - git clone git@github.com:symengine/symengine.git
  # TODO
  - cmake -DWITH_SYMENGINE_ASSERT=ON -DWITH_MPFR=ON -DCMAKE_BUILD_TYPE=Debug symengine
  - make -C symengine
  - sudo make -C symengine install
