# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r:
  - release
os:
  - linux
  - osx
sudo: false

env:
  matrix:
    - SYMENGINE_COMMIT=master
    - SYMENGINE_COMMIT=535ff3c7716c8a3ca4254e51b1b9cd5baf5d8b19

warnings_are_errors: true

notifications:
  email: false

## Use bin/install_travis.sh to install symengine C++ library
before_install:
- bash tools/setup_travis.sh
- export PATH="$HOME/conda_root/bin:$PATH"
- source activate $HOME/our_usr

