# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

apt_packages:
  - libmpc-dev
  - libmpfr-dev

before_script:
  - predir=`pwd`
  - cd /tmp
  - git clone https://github.com/symengine/symengine.git
  - cd symengine
  - cmake -DWITH_SYMENGINE_ASSERT=ON -DWITH_MPFR=ON -DCMAKE_BUILD_TYPE=Debug .
  - make
  - sudo make install
  - cd $predir
