# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r:
  - release
os:
  - linux
  - osx
sudo: false

env:
  matrix:
    - SYMENGINE_COMMIT=master
    - SYMENGINE_COMMIT=ed323f12dcb900a6d0a01f22a0ab5ac0311c030f

warnings_are_errors: true

notifications:
  email: false

## Use bin/install_travis.sh to install symengine C++ library
before_install:
- bash tools/setup_travis.sh
- export PATH="$HOME/conda_root/bin:$PATH"
- source activate $HOME/our_usr

