language: r
cache: packages
warnings_are_errors: false
os:
  - linux
  - osx
sudo: false
osx_image: xcode6.4
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - binutils-dev
    - g++-4.7
r:
  - 3.4

# env:
  # Debug builds:
  #- R_VERSION="3.3" BUILD_TYPE="Debug" WITH_BFD="yes"
  #- R_VERSION="3.4" BUILD_TYPE="Debug" WITH_BFD="yes"

  # Release builds:
  #- R_VERSION="3.3"
  #- R_VERSION="3.4"

before_install:
- |
   if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
     command curl -sSL https://rvm.io/mpapis.asc | gpg --import -;
     rvm get head || true
   fi

- export R_SOURCE_DIR=`pwd`
- export TEST_CPP="no"
- export MAKEFLAGS="-j2"
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    export CC=clang;
    export CXX=clang++;
  fi

- cd $HOME
- git clone https://github.com/symengine/symengine symengine-cpp
- cd symengine-cpp
- export SOURCE_DIR=`pwd`
- git checkout `cat ../symengine_version.txt`
- cd ..

# Setup travis for C++ library
- cd $SOURCE_DIR
- source bin/install_travis.sh

# Build C++ library
- cd $SOURCE_DIR
- bin/test_travis.sh
- unset MAKEFLAGS

- cd $R_SOURCE_DIR

notifications:
  email: false

